#!/usr/bin/env python3
"""
Train cross-dimension snapshot ML model — momentum regression.

Reads the CSV generated by `generate-snapshot-training-data.ts` and trains
a Ridge regression on the full cross-dimension feature vector to predict
forward price returns at a chosen horizon.

The model takes ~77 features (all 4 dimensions concatenated) and outputs a
trend-strength scalar in [-1, +1]:
  +1 = strong bullish momentum predicted
  -1 = strong bearish momentum predicted
   0 = no trend / ranging

Label: clip(return_pct / (3 * std), -1, 1)  — same normalization as L2a.

Model: Ridge (L2-regularized) — stable with many correlated features.
Output: models/snapshot_{asset}_{version}.onnx + .meta.json

Usage:
  python train_snapshot.py --asset BTC
  python train_snapshot.py --asset BTC --horizon 168 --alpha 10 --verify
  python train_snapshot.py --asset ETH --version v2
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import TimeSeriesSplit
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
from scipy import stats

REPO_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(REPO_ROOT / ".env")

SCHEMA_PATH = Path(__file__).parent / "feature_schema.json"
with open(SCHEMA_PATH) as f:
    FEATURE_SCHEMA = json.load(f)

# Canonical dimension order — must match generate-snapshot-training-data.ts
DIM_ORDER = ["DERIVATIVES", "ETFS", "HTF", "EXCHANGE_FLOWS"]


def feature_names_for_dim(dim: str) -> list[str]:
    """Canonical feature keys for a dimension, prefixed with dim name."""
    fs = FEATURE_SCHEMA["feature_sets"][dim]
    keys = list(fs.get("numeric", []))
    keys += [c["key"] for c in fs.get("categorical", [])]
    keys += [b["key"] for b in fs.get("boolean", [])]
    return [f"{dim}_{k}" for k in keys]


def all_feature_names(dims: list[str] | None = None) -> list[str]:
    names = []
    for dim in (dims or DIM_ORDER):
        names.extend(feature_names_for_dim(dim))
    return names


def evaluate(y_true: np.ndarray, y_pred: np.ndarray, label: str) -> dict:
    ic = float(np.corrcoef(y_true, y_pred)[0, 1]) if y_true.std() > 0 and y_pred.std() > 0 else 0.0
    _, p_val = stats.pearsonr(y_true, y_pred) if y_true.std() > 0 and y_pred.std() > 0 else (0.0, 1.0)
    nonzero = (y_true != 0) & (y_pred != 0)
    hit_rate = float((np.sign(y_true[nonzero]) == np.sign(y_pred[nonzero])).mean()) if nonzero.sum() > 0 else float("nan")
    return {
        "label": label,
        "r2": float(r2_score(y_true, y_pred)),
        "mae": float(mean_absolute_error(y_true, y_pred)),
        "pearson_ic": ic,
        "p_value": float(p_val),
        "hit_rate": hit_rate,
    }


def walk_forward_cv(X: np.ndarray, y: np.ndarray, alpha: float) -> dict:
    n_splits = min(5, max(2, len(X) // 40))
    if len(X) < 60:
        return {"folds": 0, "note": "too few samples for CV"}
    tscv = TimeSeriesSplit(n_splits=n_splits)
    oof_pred = np.full(len(X), np.nan)
    fold_metrics = []
    for fold, (tr, te) in enumerate(tscv.split(X)):
        reg = Ridge(alpha=alpha)
        reg.fit(X[tr], y[tr])
        pred = reg.predict(X[te])
        oof_pred[te] = pred
        fold_metrics.append(evaluate(y[te], pred, f"fold{fold}"))
    valid = ~np.isnan(oof_pred)
    summary = (
        evaluate(y[valid], oof_pred[valid], "oof")
        if valid.sum() > 0
        else {"label": "oof", "note": "insufficient signal"}
    )
    return {"folds": n_splits, "fold_metrics": fold_metrics, "oof": summary}


def verify_onnx(onnx_path: Path, X: np.ndarray, y: np.ndarray, output_name: str) -> dict:
    import onnxruntime as ort
    sess = ort.InferenceSession(str(onnx_path), providers=["CPUExecutionProvider"])
    inp = sess.get_inputs()[0].name
    outputs = sess.run([output_name], {inp: X.astype(np.float32)})
    pred = np.array(outputs[0]).flatten()
    return {
        "input_name": inp,
        "output_name": output_name,
        "metrics": evaluate(y, pred, "onnx_roundtrip"),
        "first_5_preds": pred[:5].tolist(),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--asset", required=True, choices=["BTC", "ETH"])
    parser.add_argument("--horizon", type=int, default=168, help="Forward return horizon in hours (default 168)")
    parser.add_argument("--version", default="v1")
    parser.add_argument("--output-dir", default=str(REPO_ROOT / "packages" / "pipeline" / "models"))
    parser.add_argument("--verify", action="store_true")
    parser.add_argument(
        "--alpha", type=float, default=10.0,
        help="Ridge L2 regularization. Higher = more regularized. Default 10 for ~77 features.",
    )
    parser.add_argument(
        "--dims", nargs="+", choices=DIM_ORDER, default=None,
        help="Dimensions to include (default: all). E.g. --dims DERIVATIVES HTF",
    )
    args = parser.parse_args()

    dims = args.dims or DIM_ORDER
    feat_names = all_feature_names(dims)
    print(f"\nAsset: {args.asset}  Horizon: {args.horizon}h  Dims: {'+'.join(dims)}  Features: {len(feat_names)}")

    # ── Load CSV ───────────────────────────────────────────────────────────────

    csv_path = REPO_ROOT / "packages" / "pipeline" / "training" / f"snapshot_training_{args.asset.lower()}.csv"
    if not csv_path.exists():
        sys.exit(
            f"Training CSV not found: {csv_path}\n"
            "Run first: pnpm ml:gen-training-data"
        )

    df = pd.read_csv(csv_path)
    df = df[df["horizon_hours"] == args.horizon].copy()
    print(f"  Loaded {len(df)} rows at {args.horizon}h horizon")

    if len(df) < 30:
        sys.exit(f"Too few rows ({len(df)}) for horizon {args.horizon}h — need at least 30.")

    # Fill missing features with 0 (older snapshots may lack newer features)
    for col in feat_names:
        if col not in df.columns:
            df[col] = 0.0
    df[feat_names] = df[feat_names].fillna(0.0)
    df = df.dropna(subset=["return_pct"])

    date_range = f"{df['timestamp'].min()[:10]} → {df['timestamp'].max()[:10]}"
    print(f"  Date range: {date_range}")

    # ── Label ─────────────────────────────────────────────────────────────────

    y_raw = df["return_pct"].to_numpy(dtype=np.float64)
    q_std = float(y_raw.std())
    if q_std == 0:
        sys.exit("All return_pct values identical — cannot train.")
    quality_scale = 3.0 * q_std
    y = np.clip(y_raw / quality_scale, -1.0, 1.0).astype(np.float64)

    print(f"  return_pct  std={q_std:.4f}  scale={quality_scale:.4f}")
    print(f"  y range: [{y.min():.3f}, {y.max():.3f}]  mean={y.mean():.3f}")

    X = df[feat_names].to_numpy(dtype=np.float32)

    # ── Per-feature IC ────────────────────────────────────────────────────────
    print("\n  Top-10 features by |Pearson IC| with label:")
    ic_vals = {}
    for i, name in enumerate(feat_names):
        col = X[:, i]
        if col.std() > 0 and y.std() > 0:
            ic_vals[name] = float(np.corrcoef(col.astype(np.float64), y)[0, 1])
        else:
            ic_vals[name] = 0.0
    top = sorted(ic_vals.items(), key=lambda kv: abs(kv[1]), reverse=True)[:10]
    for name, ic in top:
        bar = "█" * int(abs(ic) * 20)
        sign = "+" if ic >= 0 else "-"
        print(f"    {name:<45} {sign}{abs(ic):.3f}  {bar}")

    # ── CV ────────────────────────────────────────────────────────────────────
    print(f"\n  Walk-forward CV (alpha={args.alpha})…")
    cv = walk_forward_cv(X, y, args.alpha)
    if "oof" in cv:
        oof = cv["oof"]
        print(f"  OOF: R²={oof.get('r2', float('nan')):.3f}  "
              f"MAE={oof.get('mae', float('nan')):.3f}  "
              f"IC={oof.get('pearson_ic', float('nan')):+.3f}  "
              f"p={oof.get('p_value', float('nan')):.3f}")
    else:
        print(f"  CV note: {cv.get('note')}")

    # ── Train final model ─────────────────────────────────────────────────────
    print("\n  Training final model on all data…")
    final = Ridge(alpha=args.alpha)
    final.fit(X, y)
    train_metrics = evaluate(y, final.predict(X), "train_full")
    print(f"  Train: R²={train_metrics['r2']:.3f}  MAE={train_metrics['mae']:.3f}  IC={train_metrics['pearson_ic']:+.3f}")

    # ── ONNX export ───────────────────────────────────────────────────────────
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    model_name = f"snapshot_{args.asset.lower()}_{args.version}"
    onnx_path = output_dir / f"{model_name}.onnx"

    initial_type = [("X", FloatTensorType([None, len(feat_names)]))]
    onnx_model = convert_sklearn(final, initial_types=initial_type, target_opset=17)
    output_name = onnx_model.graph.output[0].name

    with open(onnx_path, "wb") as f:
        f.write(onnx_model.SerializeToString())
    print(f"\n  Exported ONNX → {onnx_path}")
    print(f"  Output name: {output_name}")

    # ── Meta ──────────────────────────────────────────────────────────────────
    meta = {
        "model_name": model_name,
        "asset": args.asset,
        "version": args.version,
        "model_type": "ridge_regression_snapshot",
        "horizon_hours": args.horizon,
        "dims": dims,
        "feature_order": feat_names,
        "n_features": len(feat_names),
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "n_samples": len(df),
        "date_range": {"start": df["timestamp"].min(), "end": df["timestamp"].max()},
        "quality_scale": quality_scale,
        "regularization": {"penalty": "l2", "alpha": args.alpha},
        "onnx_output_name": output_name,
        "cv": cv,
        "training_metrics": train_metrics,
        "top_features_by_ic": [{"feature": n, "ic": ic} for n, ic in top],
    }
    meta_path = output_dir / f"{model_name}.meta.json"
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"  Meta       → {meta_path}")

    # ── Verify ────────────────────────────────────────────────────────────────
    if args.verify:
        print("\n  Verifying ONNX roundtrip…")
        vr = verify_onnx(onnx_path, X, y, output_name)
        print(f"  ONNX R²={vr['metrics']['r2']:.3f}  IC={vr['metrics']['pearson_ic']:+.3f}")
        print(f"  First 5 preds: {[f'{p:.3f}' for p in vr['first_5_preds']]}")

    print(f"\n  Done. Model: {model_name}\n")


if __name__ == "__main__":
    main()
